# Generated by Django 2.0.1 on 2018-02-23 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('power_score', models.IntegerField(default=0)),
                ('durability', models.IntegerField(default=0)),
                ('mass', models.IntegerField(default=0)),
                ('crafteable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='piezas',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Rarity'),
        ),
    ]
