# Generated by Django 2.0.1 on 2018-02-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piezas',
            new_name='Pieza',
        ),
    ]
