# Generated by Django 2.0.1 on 2018-02-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180223_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
    ]
