# Generated by Django 2.0.1 on 2018-02-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rarity_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='nommbre',
            new_name='nombre',
        ),
    ]
