# Generated by Django 2.0.1 on 2018-02-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180228_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(null=True, upload_to='piezas_imagenes'),
        ),
    ]
