# Generated by Django 2.0.1 on 2018-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_pieza_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(null=True, upload_to='uploads/piezas_imagenes'),
        ),
    ]
