# Generated by Django 2.0.1 on 2018-03-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180301_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(null=True, upload_to='piezas_imagenes'),
        ),
    ]
